version: '3.8'

services:
  rcm-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=gemini-2.0-flash
      - DATABASE_URL=postgresql://rcm_user:rcm_password@postgres:5432/rcm_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=production
    depends_on:
      - postgres
    volumes:
      - ./configs:/app/configs
      - ./rules:/app/rules
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=rcm_db
      - POSTGRES_USER=rcm_user
      - POSTGRES_PASSWORD=rcm_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: